In [1]:
import os
import cv2
import time 

In [2]:
img_bgr = cv2.imread('./img/ame-gasho-25.png')
# im_gray = cv2.imread('data/src/lena.jpg', 0 cv2.IMREAD_GRAYSCALE)



In [3]:
print(type(img_bgr))
# <class 'numpy.ndarray'>

print()
# (225, 400)

print(img_bgr)
# uint8

<class 'numpy.ndarray'>

[[[156 149 132]
  [156 148 133]
  [156 148 132]
  ...
  [154 147 132]
  [154 147 132]
  [154 147 132]]

 [[157 149 133]
  [156 148 132]
  [156 148 132]
  ...
  [154 147 132]
  [154 147 132]
  [154 147 132]]

 [[157 149 133]
  [157 149 133]
  [157 149 133]
  ...
  [154 147 132]
  [154 147 132]
  [154 147 132]]

 ...

 [[ 55  73 152]
  [ 54  72 152]
  [ 64  84 173]
  ...
  [ 81 101 189]
  [ 76  97 187]
  [ 85 105 190]]

 [[ 59  78 161]
  [ 52  69 144]
  [ 51  69 144]
  ...
  [ 78  99 189]
  [ 82 102 189]
  [ 91 111 193]]

 [[ 63  85 174]
  [ 57  76 157]
  [ 56  74 153]
  ...
  [ 69  91 185]
  [ 75  96 187]
  [ 76  97 187]]]


In [ ]:
datetime_now = time.time();
cv2.imwrite(str(datetime_now)+"out.jpg", img_bgr)


In [ ]:
cv2.imshow("result", img_bgr)
cv2.waitKey(0)
cv2.destroyAllWindows()
